[loadbalancers]
lb01 ansible_host=192.168.56.10

[webservers]
app01 ansible_host=192.168.56.11
app02 ansible_host=192.168.56.12

[all:vars]
# Tell Ansible to connect as the 'vagrant' user
ansible_user=vagrant

# Point Ansible to the automatic private SSH keys managed by Vagrant
ansible_ssh_private_key_file=.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key

# Bypass strict host key checking for quick local development
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
