terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
  profile = "default"
}

variable "aws_region" {
  type    = string
  default = "eu-central-1"
}

variable "target_ami_id" {
  type        = string
  description = "The AMI ID generated by your Packer build execution"
}
